server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/employees/**

management:
  tracing:
    sampling:
      probability: 1.0