server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.springframework.cloud.config: DEBUG